name: Run Scheduled Task

on:
  schedule:
    # Run at 12:00 AM IST daily (which is 6:30 PM UTC)
    - cron: '30 18 * * *'

jobs:
  run-api-call:
    runs-on: ubuntu-latest

    steps:
      - name: Call top_stocks API
        run: |
          curl -X GET https://rs-analysis-tool.onrender.com/top-stocks
